version: 2

sources:
  - name: raw_source
    database: DBT_PROJECT_DB
    schema: RAW_SCHEMA
    tables:
      - name: CUSTOMER
        identifier: CUS
      - name: ORDERS
      - name: ORDER_ITEMS
      - name: PRODUCTS
      - name: PAYMENTS